### ISSUE TITLE
Add .gitattributes and ignore .github folder

### ISSUE THREAD

**Issue by volfkarlo** [infinum/eightshift-boilerplate-internal#11]
`.gitattributes` will tell the git command what to clone and what not to clone. Currently on cloning or setting up the project, we get `.github` folder which is not necessary. 

https://git-scm.com/docs/gitattributes

**Comment by IvanGrginovInf** [comment]
Added those 2 to `.gitattributes` although it seems it only ignores them on `export`, not on `clone`.

To rectify this, the setup script now deletes `.github` folder as part of the last `cleanup` step.
